version: "3"

services:
  mdsite:
    image: mdsite
    container_name: mdsite
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile

networks:
  mongo-docker_mongo_net:
    external: true